[package]
name = "kanji-frequency"
version = "0.1.0"
authors = ["slay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epub = "^1.2.2"
regex = "^1"
lazy_static= "^1.4.0"